{
 "title": "Corona stats",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Region",
    "query": " show tag values  with key= \"Combined_Key\""
   },
   { "name": "max_entries", "query": "10,20,50,100" },
   { "name": "min_value", "query": "0,10,20,30,100" }
  ]
 },
 "panels": [
  {
   "title": "Data From Timeseries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_Country_Region $tag_Province_State Infected",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Country_Region" ], "type": "tag" },
      { "params": [ "Province_State" ], "type": "tag" }
     ],
     "measurement": "timeseries",
     "query": "SELECT sum(\"Confirmed\") FROM \"autogen\".\"timeseries\" WHERE (\"Country_Region\" =~ /^$Region$/ OR \"Province_State\" =~ /^$Region$/ AND \"confirmed\" > $min_value) AND $timeFilter GROUP BY time($__interval), \"Country_Region\", \"Province_State\"",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Country_Region", "operator": "=~", "value": "/^$Region$/" },
      { "condition": "OR", "key": "Province_State", "operator": "=~", "value": "/^$Region$/" },
      { "condition": "AND", "key": "confirmed", "operator": ">", "value": "$min_value" }
     ]
    },
    {
     "alias": "$tag_Country_Region $tag_Province_State Deaths",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Country_Region" ], "type": "tag" },
      { "params": [ "Province_State" ], "type": "tag" }
     ],
     "measurement": "timeseries",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Country_Region", "operator": "=~", "value": "/^$Region$/" },
      { "condition": "OR", "key": "Province_State", "operator": "=~", "value": "/^$Region$/" },
      { "condition": "AND", "key": "Deaths", "operator": ">", "value": "$min_value" }
     ]
    }
   ]
  },
  {
   "title": "Data From individual days",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_Combined_Key Confirmed cases",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "Combined_Key" ], "type": "tag" }
     ],
     "measurement": "cases",
     "query": "SELECT sum(\"Confirmed\"), sum(\"Deaths\") FROM \"autogen\".\"cases\" WHERE (\"Combined_Key\" =~ /^$Region$/) AND $timeFilter GROUP BY time(24h), \"Combined_Key\"",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "slimit": "$max_entries",
     "tags": [
      { "key": "Combined_Key", "operator": "=~", "value": "/^$Region$/" }
     ]
    },
    {
     "alias": "$tag_Combined_Key Deaths",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "Combined_Key" ], "type": "tag" }
     ],
     "measurement": "cases",
     "query": "SELECT sum(\"Deaths\") FROM \"autogen\".\"cases\" WHERE (\"Combined_Key\" =~ /^$Region$/) AND $timeFilter GROUP BY time(24h), \"Combined_Key\"",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "slimit": "$max_entries",
     "tags": [
      { "key": "Combined_Key", "operator": "=~", "value": "/^$Region$/" }
     ]
    }
   ]
  },
  {
   "title": "Data From Timeseries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_Country_Region $tag_Province_State Infected",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Country_Region" ], "type": "tag" },
      { "params": [ "Province_State" ], "type": "tag" }
     ],
     "measurement": "timeseries",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "slimit": "$max_entries",
     "tags": [
      { "key": "Country_Region", "operator": "=~", "value": "/^$Region$/" },
      { "condition": "OR", "key": "Province_State", "operator": "=~", "value": "/^$Region$/" },
      { "condition": "AND", "key": "Confirmed", "operator": "=", "value": "$min_value" }
     ]
    },
    {
     "alias": "$tag_Country_Region $tag_Province_State Deaths",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Country_Region" ], "type": "tag" },
      { "params": [ "Province_State" ], "type": "tag" }
     ],
     "measurement": "timeseries",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "slimit": "$max_entries",
     "tags": [
      { "key": "Country_Region", "operator": "=~", "value": "/^$Region$/" },
      { "condition": "OR", "key": "Province_State", "operator": "=~", "value": "/^$Region$/" },
      { "condition": "AND", "key": "Deaths", "operator": "=~", "value": "/^$min_value$/" }
     ]
    }
   ]
  },
  {
   "title": "Data From individual Days",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_Combined_Key Confirmed cases",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "Combined_Key" ], "type": "tag" }
     ],
     "measurement": "cases",
     "query": "SELECT sum(\"Confirmed\"), sum(\"Deaths\") FROM \"autogen\".\"cases\" WHERE (\"Combined_Key\" =~ /^$Region$/) AND $timeFilter GROUP BY time(24h), \"Combined_Key\"",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Combined_Key", "operator": "=~", "value": "/^$Region$/" }
     ]
    },
    {
     "alias": "$tag_Combined_Key Deaths",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "Combined_Key" ], "type": "tag" }
     ],
     "measurement": "cases",
     "query": "SELECT sum(\"Deaths\") FROM \"autogen\".\"cases\" WHERE (\"Combined_Key\" =~ /^$Region$/) AND $timeFilter GROUP BY time(24h), \"Combined_Key\"",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Combined_Key", "operator": "=~", "value": "/^$Region$/" }
     ]
    }
   ]
  },
  {
   "title": "Detailed Overview $Region ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "repeat": "Region",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col  $tag_Country_Region",
     "groupBy": [
      { "params": [ "Country_Region" ], "type": "tag" }
     ],
     "measurement": "timeseries",
     "query": "SELECT Recovered,\"Confirmed\",\"Deaths\"FROM \"timeseries\" WHERE(\"Country_Region\" =~ /^$Region$/ OR \"Province_State\" =~ /^$Region$/ ) AND $timeFilter GROUP BY \"Country_Region\"",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" }
      ],
      [
       { "params": [ "Deaths" ], "type": "field" }
      ],
      [
       { "params": [ "Recovered" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Country_Region", "operator": "=", "value": "Germany" }
     ]
    },
    {
     "alias": "Active $tag_Country_Region",
     "groupBy": [
      { "params": [ "Country_Region" ], "type": "tag" }
     ],
     "measurement": "timeseries",
     "query": "SELECT \"Confirmed\"- \"Deaths\"-\"Recovered\" FROM \"timeseries\" WHERE(\"Country_Region\" =~ /^$Region$/ OR \"Province_State\" =~ /^$Region$/ ) AND $timeFilter GROUP BY \"Country_Region\"",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" }
      ],
      [
       { "params": [ "Deaths" ], "type": "field" }
      ],
      [
       { "params": [ "Recovered" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Country_Region", "operator": "=", "value": "Germany" }
     ]
    }
   ]
  },
  {
   "title": "Detailed Overview $Region ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "repeat": "Region",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col  $tag_Country_Region",
     "groupBy": [
      { "params": [ "Country_Region" ], "type": "tag" }
     ],
     "measurement": "timeseries",
     "query": "SELECT Recovered,\"Confirmed\",\"Deaths\"FROM \"timeseries\" WHERE(\"Country_Region\" =~ /^$Region$/ OR \"Province_State\" =~ /^$Region$/ ) AND $timeFilter GROUP BY \"Country_Region\"",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" }
      ],
      [
       { "params": [ "Deaths" ], "type": "field" }
      ],
      [
       { "params": [ "Recovered" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Country_Region", "operator": "=", "value": "Germany" }
     ]
    },
    {
     "alias": "Active $tag_Country_Region",
     "groupBy": [
      { "params": [ "Country_Region" ], "type": "tag" }
     ],
     "measurement": "timeseries",
     "query": "SELECT \"Confirmed\"- \"Deaths\"-\"Recovered\" FROM \"timeseries\" WHERE(\"Country_Region\" =~ /^$Region$/ OR \"Province_State\" =~ /^$Region$/ ) AND $timeFilter GROUP BY \"Country_Region\"",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" }
      ],
      [
       { "params": [ "Deaths" ], "type": "field" }
      ],
      [
       { "params": [ "Recovered" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Country_Region", "operator": "=", "value": "Germany" }
     ]
    }
   ]
  },
  {
   "title": "$Region Deathrate from timeseries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "repeat": "Region",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$Region Deathrate",
     "measurement": "timeseries",
     "query": "SELECT \"Deaths\" /Confirmed FROM \"autogen\".\"timeseries\" WHERE ((\"Country_Region\" =~ /^$Region$/ OR \"Province_State\" =~ /^$Region$/) AND \"Deaths\" > $min_value) AND $timeFilter",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       { "params": [ "/Confirmed" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "Country_Region", "operator": "=~", "value": "/^$Region$/" },
      { "condition": "OR", "key": "Province_State", "operator": "=~", "value": "/^$Region$/" },
      { "condition": "AND", "key": "Deaths", "operator": ">", "value": "$min_value" }
     ]
    }
   ]
  },
  {
   "title": "$Region Deathrate from individual Days",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "repeat": "Region",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$Region $tag_Admin2 Deathrate",
     "groupBy": [
      { "params": [ "Combined_Key" ], "type": "tag" }
     ],
     "measurement": "cases",
     "query": "SELECT \"Deaths\" /Confirmed FROM \"autogen\".\"cases\" WHERE (\"Combined_Key\" =~ /^$Region$/) AND $timeFilter GROUP BY \"Admin2\", \"Combined_Key\"",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       { "params": [ "/Confirmed" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "Combined_Key", "operator": "=~", "value": "/^$Region$/" },
      { "condition": "AND", "key": "Deaths", "operator": ">", "value": "$min_value" }
     ]
    }
   ]
  }
 ]
}